Remove id field for compatibility issue.
This fix just removes 'id' field.
It is [internally reserved on 0.10.1](https://github.com/hashicorp/terraform/blob/v0.11.11/CHANGELOG.md#0101-august-15-2017)
and user get following error when build with terraform 0.12.

```
sugi@sugi-x1c:~/t% terraform-0.11.14 apply

Error: provider.papertrail: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

3 errors occurred:
	* resource papertrail_system: id is a reserved field name
	* resource papertrail_group: id is a reserved field name
	* resource papertrail_search: id is a reserved field name
```

Update terraform module to v0.12.5.

Move to bsquare